CREATE DATABASE CASE;
USE CASE ;
GO 
/*==============================================================*/
/* TABELA: STG_DESPESA_PUBLICA                                    */
/*==============================================================*/
IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.[STG_DESPESA_PUBLICA]')
            AND   TYPE = 'U')
   DROP TABLE DBO.[STG_DESPESA_PUBLICA]
   GO
CREATE TABLE [STG_DESPESA_PUBLICA](
	[EXERCICIO] [VARCHAR](50) NULL,
	[COD_ORGAO_SUPERIOR] [INT] NULL,
	[NOME_ORGAO_SUPERIOR] [VARCHAR](150) NULL,
	[COD_ORGAO_SUBORDINADO] [INT] NULL,
	[NOME_ORGAO_SUBORDINADO] [VARCHAR](150) NULL,
	[COD_UNIDADE_GESTORA] [INT] NULL,
	[NOME_UNIDADE_GESTORA] [VARCHAR](50) NULL,
	[COD_GESTAO] [INT] NULL,
	[NOME_GESTAO] [VARCHAR](50) NULL,
	[COD_UNIDADE_ORCAMENTARIA] [INT] NULL,
	[NOME_UNIDADE_ORCAMENTARIA] [VARCHAR](150) NULL,
	[COD_FUNCAO] [INT] NULL,
	[NOME_FUNCAO] [VARCHAR](50) NULL,
	[COD_SUBFUNCAO] [INT] NULL,
	[NOME_SUBFUNCAO] [VARCHAR](150) NULL,
	[COD_PROGRAMA_ORCAMENTARIA] [INT] NULL,
	[NOME_PROGRAMA_ORCAMENTARIA] [VARCHAR](150) NULL,
	[COD_ACAO] [VARCHAR](50) NULL,
	[NOME_ACAO] [VARCHAR](255) NULL,
	[COD_PROGRAMA_GOVERNO] [VARCHAR](50) NULL,
	[NOME_PROGRAMA_GOVERSO] [VARCHAR](150) NULL,
	[COD_GRUPO_DESPESA] [INT] NULL,
	[NOME_GRUPO_DESPESA] [VARCHAR](150) NULL,
	[COD_ELEMENTO_DESPESA] [INT] NULL,
	[NOME_ELEMENTO_DESPESA] [VARCHAR](150) NULL,
	[COD_MODALIDADE_DESPESA] [INT] NULL,
	[MODALIDADE_DESPESA] [VARCHAR](150) NULL,
	[VR_EMPENHADO] [DECIMAL](28, 0) NULL,
	[VR_LIQUIDO] [DECIMAL](28, 0) NULL,
	[VR_PAGO] [DECIMAL](28, 0) NULL,
	[VR_RESTO_PAGAR_INSCRITO] [DECIMAL](28, 0) NULL,
	[VR_RETO_PAGAR_CANCELADO] [DECIMAL](28, 0) NULL,
	[VR_RESTO_PAGAR_PAGO] [DECIMAL](28, 0) NULL
) 

GO


/*==============================================================*/
/* TABELA: STG_RECEITA                                    */
/*==============================================================*/
IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.STG_RECEITA')
            AND   TYPE = 'U')
   DROP TABLE DBO.STG_RECEITA
   GO
   
CREATE TABLE [STG_RECEITA] (
    [CODIGO_ORGAO_SUPERIOR] VARCHAR(50),
    [NOME_ORGAO_SUPERIOR] VARCHAR(255),
    [CODIGO_ORGAO] INT,
    [NOME_ORGAO] VARCHAR(255),
    [CODIGO_UNIDADE_GESTORA] INT,
    [NOME_UNIDADE_GESTORA] VARCHAR(255),
    [CATEGORIA_ECONOMICA] VARCHAR(50),
    [ORIGEM_RECEITA] VARCHAR(255),
    [ESPECIE_RECEITA] VARCHAR(255),
    [DETALHAMENTO] VARCHAR(255),
    [VALOR_PREVISTO_ATUALIZADO] NUMERIC(18,0),
    [VALOR_LANCADO] NUMERIC(18,0),
    [VALOR_REALIZADO] NUMERIC(18,0),
    [PERCENTUAL_REALIZADO] NUMERIC(18,0),
    [DATA_LANÇAMENTO] VARCHAR(50),
    [ANO_EXERCICIO] INT
)
GO


 IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.DIM_ORGAO_SUPERIOR')
            AND   TYPE = 'U')
   DROP TABLE DBO.DIM_ORGAO_SUPERIOR
GO

/*==============================================================*/
/* TABELA: DIM_ORGAO_SUPERIOR                                    */
/*==============================================================*/
CREATE TABLE DBO.DIM_ORGAO_SUPERIOR (
   SK_ORGAO_SUPERIOR    INT                  IDENTITY(1, 1),
   COD_ORGAO_SUPERIOR   INT                  NULL,
   NOME_ORGAO_SUPERIOR  VARCHAR(150)         COLLATE LATIN1_GENERAL_CI_AS NULL,
   DT_ATUALIZACAO       DATE                 NULL,
   CONSTRAINT PK_DIM_ORGAO_SUPERIOR PRIMARY KEY (SK_ORGAO_SUPERIOR)
         ON "PRIMARY"
)
GO

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.DIM_FUNCAO_DESPESA')
            AND   TYPE = 'U')
   DROP TABLE DBO.DIM_FUNCAO_DESPESA
GO

/*==============================================================*/
/* TABELA: DIM_FUNCAO_DESPESA                                    */
/*==============================================================*/
CREATE TABLE DBO.DIM_FUNCAO_DESPESA (
   SK_FUNCAO_DESPESA    INT                  IDENTITY(1, 1),
   COD_FUNCAO_DESPESA   INT                  NOT NULL,
   NOME_FUNCAO_DESPESA  VARCHAR(100)         COLLATE LATIN1_GENERAL_CI_AS NULL,
   DT_ATUALIZACAO       DATE                 NULL,
   CONSTRAINT PK_DIM_FUNCAO_DESPESA PRIMARY KEY (SK_FUNCAO_DESPESA)
         ON "PRIMARY"
)

GO


IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.DIM_ORGAO_SUBORDINADO')
            AND   TYPE = 'U')
   DROP TABLE DBO.DIM_ORGAO_SUBORDINADO
GO

/*==============================================================*/
/* TABELA: DIM_ORGAO_SUBORDINADO                                 */
/*==============================================================*/
CREATE TABLE DBO.DIM_ORGAO_SUBORDINADO (
   SK_ORGAO_SUBORDINADO INT                  IDENTITY(1, 1),
   COD_ORGAO_SUBORDINADO INT                  NULL,
   NOME_ORGAO_SUBORDINADO VARCHAR(150)         COLLATE LATIN1_GENERAL_CI_AS NULL,
   DT_ATUALIZACAO       DATE                 NULL,
   CONSTRAINT PK_DIM_ORGAO_SUBORDINADO PRIMARY KEY (SK_ORGAO_SUBORDINADO)
         ON "PRIMARY"
)

GO


IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.DIM_GRUPO_DESPESA')
            AND   TYPE = 'U')
   DROP TABLE DBO.DIM_GRUPO_DESPESA
GO

/*==============================================================*/
/* TABELA: DIM_GRUPO_DESPESA                                     */
/*==============================================================*/
CREATE TABLE DBO.DIM_GRUPO_DESPESA (
   SK_GRUPO_DESPESA     INT                  IDENTITY(1, 1),
   COD_GRUPO_DESPESA    INT                  NOT NULL,
   NOME_GRUPO_DESPESA   VARCHAR(100)         COLLATE LATIN1_GENERAL_CI_AS NULL,
   DT_ATUALIZACAO       DATE                 NULL,
   CONSTRAINT PK_DIM_GRUPO_DESPESA PRIMARY KEY (SK_GRUPO_DESPESA)
         ON "PRIMARY"
)

GO

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.DIM_MODALIDADE_DESPESA')
            AND   TYPE = 'U')
   DROP TABLE DBO.DIM_MODALIDADE_DESPESA
GO

/*==============================================================*/
/* TABELA: DIM_MODALIDADE_DESPESA                                */
/*==============================================================*/
CREATE TABLE DBO.DIM_MODALIDADE_DESPESA (
   SK_MODALIDADE_DESPESA INT                  IDENTITY(1, 1),
   COD_MODALIDADE_DESPESA INT                  NULL,
   MODALIDADE_DESPESA   VARCHAR(150)         COLLATE LATIN1_GENERAL_CI_AS NULL,
   DT_ATUALIZACAO       DATE                 NULL,
   CONSTRAINT PK_DIM_MODALIDADE_DESPESA PRIMARY KEY (SK_MODALIDADE_DESPESA)
         ON "PRIMARY"
)

GO

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.DIM_TEMPO')
            AND   TYPE = 'U')
   DROP TABLE DBO.DIM_TEMPO
GO

/*==============================================================*/
/* TABELA: DIM_TEMPO                                             */
/*==============================================================*/
CREATE TABLE DBO.DIM_TEMPO(
 SK_DIM_TEMPO INT IDENTITY(1,1) NOT NULL ,
 DATA varchar(8) NOT NULL,
 ANO SMALLINT NOT NULL,
 MES SMALLINT NOT NULL,
 
 
 CONSTRAINT PK__DIM_TEMPO PRIMARY KEY (SK_DIM_TEMPO)
         ON "PRIMARY"
 
 )

 DECLARE @DATAINICIAL DATE, @DATAFINAL DATE, @DATA DATE, 
    @ANO SMALLINT, @MES SMALLINT

--INFORME AQUI O PERÍODO PARA O QUAL DESEJA CRIAR OS DADOS
SET @DATAINICIAL = '2018-01-1 00:00:00.00'
SET @DATAFINAL = '2020-12-31 00:00:00.00'
SELECT GETDATE()
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
 SET @DATA = @DATAINICIAL
 SET @ANO = YEAR(@DATA)
 SET @MES = MONTH(@DATA)

INSERT INTO DBO.DIM_TEMPO
 SELECT distinct 
 FORMAT(@DATA,'yyyy-MM')
 ,@ANO
 ,@MES
 
 SET @DATAINICIAL = DATEADD(DAY,1,@DATAINICIAL) 
END


GO

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.FATO_DESPESA')
            AND   TYPE = 'U')
   DROP TABLE DBO.FATO_DESPESA
GO

/*==============================================================*/
/* TABELA: FATO_DESPESA                                          */
/*==============================================================*/
CREATE TABLE DBO.FATO_DESPESA (
   SK_FT_DESPESA        INT                  IDENTITY(1, 1),
   SK_ORGAO_SUPERIOR    INT                  NOT NULL,
   SK_MODALIDADE_DESPESA INT                  NOT NULL,
   SK_ORGAO_SUBORDINADO INT                  NOT NULL,
   SK_DIM_TEMPO         INT                  NOT NULL,
   SK_FUNCAO_DESPESA    INT                  NOT NULL,
   SK_GRUPO_DESPESA     INT                  NOT NULL,
   VR_EMPENHADO         DECIMAL(18,2)        NOT NULL,
   VR_LIQUIDO           DECIMAL(18,2)        NOT NULL,
   VR_PAGO              DECIMAL(18,2)        NOT NULL,
   VR_RESTO_PAGAR_INSCRITO DECIMAL(18,2)        NOT NULL,
   VR_RETO_PAGAR_CANCELADO DECIMAL(18,2)        NOT NULL,
   VR_RESTO_PAGAR_PAGO  DECIMAL(18,2)        NOT NULL,
   DT_ATUALIZACAO       DATETIME             NULL,
   CONSTRAINT [PK_FATO_DESPESA] PRIMARY KEY CLUSTERED 
(
	[SK_FT_DESPESA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO


IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DBO.[FATO_RECEITA]')
            AND   TYPE = 'U')
   DROP TABLE DBO.[FATO_RECEITA]
GO

/*==============================================================*/
/* TABELA: FATO_RECEITA                                          */
/*==============================================================*/


CREATE TABLE [DBO].[FATO_RECEITA](
	[SK_FT_RECEITA] [INT] IDENTITY(1,1) NOT NULL,
	[SK_ORGAO_SUPERIOR] [INT] NOT NULL,
	[SK_ORGAO_SUBORDINADO] [INT] NOT NULL,
	[SK_DIM_TEMPO] [INT] NOT NULL,
	VALOR_PREVISTO_ATUALIZADO [DECIMAL](18, 2) NOT NULL,
	VALOR_LANCADO [DECIMAL](18, 2) NOT NULL,
	VALOR_REALIZADO [DECIMAL](18, 2) NOT NULL,
	PERCENTUAL_REALIZADO [DECIMAL](18, 2) NOT NULL,
	DT_ATUALIZACAO DATE, 
	 CONSTRAINT [PK_FATO_RECEITA] PRIMARY KEY CLUSTERED 
(
	[SK_FT_RECEITA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/*==============================================================*/ 
/*ADD CONSTRAINTS   FATO_DESPESA                             */ 
/*==============================================================*/
/* 
ALTER TABLE FATO_DESPESA 
  ADD CONSTRAINT FK_FATO_DES_DIM_MODAL_DIM_MODA FOREIGN KEY ( 
  SK_MODALIDADE_DESPESA) REFERENCES DIM_MODALIDADE_DESPESA ( 
  SK_MODALIDADE_DESPESA) 

ALTER TABLE FATO_DESPESA 
  ADD CONSTRAINT FK_FATO_DES_DIM_ORGAO_DIM_ORGA FOREIGN KEY ( 
  SK_ORGAO_SUBORDINADO) REFERENCES DIM_ORGAO_SUBORDINADO (SK_ORGAO_SUBORDINADO) 

ALTER TABLE FATO_DESPESA 
  ADD CONSTRAINT FK_FATO_DES_DIM_ORGAO_SUPERIOR FOREIGN KEY (SK_ORGAO_SUPERIOR) 
  REFERENCES DIM_ORGAO_SUPERIOR (SK_ORGAO_SUPERIOR) 

ALTER TABLE FATO_DESPESA 
  ADD CONSTRAINT FK_FATO_DES_DIM_TEMPO_DIM_TEMP FOREIGN KEY (SK_DIM_TEMPO) 
  REFERENCES DBO.DIM_TEMPO (SK_DIM_TEMPO) 

ALTER TABLE FATO_DESPESA 
  ADD CONSTRAINT FK_FATO_DIM_FUNCAO_DESPESA FOREIGN KEY (SK_FUNCAO_DESPESA) 
  REFERENCES DBO.DIM_FUNCAO_DESPESA (SK_FUNCAO_DESPESA) 

ALTER TABLE FATO_DESPESA 
  ADD CONSTRAINT FK_FATO_DES_DIM_GRUPO_DESPESA FOREIGN KEY (SK_GRUPO_DESPESA) 
  REFERENCES DBO.DIM_GRUPO_DESPESA (SK_GRUPO_DESPESA) 

/*==============================================================*/ 
/*ADD CONSTRAINTS   FATO_RECEITA                             */ 
/*==============================================================*/ 
/*
ALTER TABLE FATO_RECEITA 
  ADD CONSTRAINT FK_FATO_RES_DIM_ORGAO_DIM_ORGA FOREIGN KEY ( SK_ORGAO_SUPERIOR)
  REFERENCES DIM_ORGAO_SUPERIOR (SK_ORGAO_SUPERIOR) 
    
  
  ALTER TABLE FATO_RECEITA 
  ADD CONSTRAINT FK_FATO_RES_DIM_ORGAO_SUBORDINADO_DIM_ORGAO_SUBORDINADO FOREIGN KEY ( SK_ORGAO_SUBORDINADO)
  REFERENCES DIM_ORGAO_SUBORDINADO (SK_ORGAO_SUBORDINADO) 
  
  
  
  ALTER TABLE FATO_RECEITA 
  ADD CONSTRAINT FK_FATO_RES_DIM_TEMPO_DIM_TEMP FOREIGN KEY ( SK_DIM_TEMPO)
  REFERENCES DIM_TEMPO (SK_DIM_TEMPO) 

*/




